services:
  postgres:
    image: postgres:16
    container_name: pg-main
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: supersecret
    volumes:
      - ./data:/var/lib/postgresql/data
    # (Opsional) publish port ke host kalau mau akses dari LAN / tools di Windows
    # Kalau hanya dipakai antar-container via appsnet, baris di bawah bisa DIHILANGKAN
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U appuser -d appdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped